### ISSUE TITLE
recieving updates but not posting on CurseForge/Modrinth? Why

### ISSUE THREAD

**Issue by walksanatora** [2xsaiko/retrocomputers#10]
Just wondering as i just found this mod, it would be nice if there was more of a wiki on what to do in this mod

**Comment by CodeByAidan** [comment]
I will be volunteering answering questions if you want. Just reply to this!

**Comment by walksanatora** [comment]
Ok. Why are there being github release published, but not cf/modrinth updates

**Comment by CodeByAidan** [comment]
I'm not the creator, so I can't answer that... I thought you wanted to ask questions on the "wiki" that is not present. I can help better on that.

**Comment by dblsaiko** [comment]
4.x hasn't been uploaded anywhere because it's broken.
