### ISSUE TITLE
Is this still active?

### ISSUE THREAD

**Issue by DariusSG** [2xsaiko/retrocomputers#5]

**Comment by dblsaiko** [comment]
In theory, yes, I've just kinda hit a roadblock with implementing the last part of it (bundled cable support, mainly), I might have to redesign that part. Right now I'm working on something that actually has to do with this/my other mods.

**Comment by LukeTech2006** [comment]
Well, at this Point it seems *pretty* dead...

**Comment by xJon** [comment]
Would make a great addition to [Tekkit 2](https://www.technicpack.net/modpack/tekkit-2) if this was revived, ideally as an extension to Project Red
