### ISSUE TITLE
What language?

### ISSUE THREAD

**Issue by PublicVoidUpdate** [2xsaiko/retrocomputers#6]
What programing language does this use? Is there a wiki on how this works? Thanks you for your time

**Comment by dblsaiko** [comment]
The language it comes with is FORTH, unfortunately I don't really have my own documentation on it but I kept it pretty similar to RedPower Control's MineOS which you'll be able to find a lot of documentation on, like this one: https://tekkitclassic.fandom.com/wiki/Tutorial/Redpower_Programming
