### ISSUE TITLE
Permission to use floppy disk drive sounds from 1.12.2 version of this mod?

### ISSUE THREAD

**Issue by TalonFloof** [2xsaiko/retrocomputers#8]
Hello, @2xsaiko. I noticed that the older 1.12.2 version of this mod contained some unused floppy disk drive sound samples. I really liked the sounds and I was curious if I could use them for a project I've been working on.

**Comment by dblsaiko** [comment]
They were recorded from my 1571 disk drive, and were actually used in the 1.7.10 version of the mod. But sure, you can use them!

**Comment by TalonFloof** [comment]
Thank you very much!

**Comment by TalonFloof** [comment]
Also, there is a 1.7.10 version? I can't seem to find the JAR file on CurseForge.

**Comment by dblsaiko** [comment]
Uhh, 1.12 I mean, the 1.x versions of the mod should use these sounds.

**Comment by TalonFloof** [comment]
Oh, that makes sense.
